# Generated by Django 5.1.6 on 2025-03-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorSession',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='spotify_access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='token_expires_at',
            new_name='spotify_last_sync',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='refresh_token',
            new_name='spotify_refresh_token',
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_token_expires_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
