# Generated by Django 5.1.6 on 2025-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('result_data', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'analytics history',
                'verbose_name_plural': 'analytics histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('analysis_data', models.JSONField()),
                ('popularity', models.IntegerField()),
                ('genres', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'artist analysis',
                'verbose_name_plural': 'artist analyses',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('analysis_data', models.JSONField()),
                ('track_count', models.IntegerField(default=0)),
                ('total_duration_ms', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'playlist analysis',
                'verbose_name_plural': 'playlist analyses',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='PublicTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('genre', 'Genre Distribution'), ('artist', 'Artist Popularity'), ('feature', 'Audio Features'), ('tempo', 'Tempo Distribution'), ('key', 'Key Distribution'), ('general', 'General Trends')], max_length=50)),
                ('trend_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'public trend',
                'verbose_name_plural': 'public trends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'track features',
                'verbose_name_plural': 'track features',
                'ordering': ['-created_at'],
            },
        ),
    ]
